### ISSUE TITLE
Featured Tournaments

### ISSUE THREAD

**Issue by behindcurtain3** [okayzed/dmangame#10]
A cool way to encourage more participants would be to hold monthly tournaments. You should have to enter your AI into each tournament by a cutoff date/time. Something like, hold a tournament the first sunday of each month with cutoff times at 8am. There could be several types of tournaments: default, village, macro, random etc. Also 1v1, 1v1v1 etc. These could be ran parallel or a different one chosen each month. Watching a match live from the app engine would be awesome also but I don't know how feasible this would be.

The point is to have something that could be marketed and generate interest from the devs. Something to bring us together once a month to chat about and see our progress.

**Comment by okayzed** [comment]
this is done, as far as i know
